version: '3'
services:

  nginx:
    # image: nginx:stable-alpine
    container_name: nginx
    build: ./docker/nginx
    image: nginx-www-data
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    # reload every 6 hours when nginx renovation will be needed
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      # reemplazamos la instalación de nginx
      - ./nginx:/etc/nginx
      # conectamos los certificados con el host
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./log/nginx:/var/log/nginx
      - ./apps:/usr/share/nginx/html

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    # automatic check renovation needed every 12 hours
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      # .well-known directory?
      - ./certbot/www:/var/www/certbot
