version: '3'
services:

  nginx:
    # image: nginx:stable-alpine has an error because www-data user is not created on the default image
    container_name: nginx-alpine-server
    build: ./docker/nginx-alpine
    image: nginx-alpine-server
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    # reload every 6 hours when nginx renovation will be needed
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      # reemplazamos la instalación de nginx
      - ./nginx:/etc/nginx
      # conectamos los certificados con el host
      - ./certbot/conf:/etc/letsencrypt
      # .well-known directory keys
      - ./certbot/www:/var/www/certbot
      - ./log/nginx:/var/log/nginx
      # apps directory depends on conf.d files to link to this directory
      - ./apps:/var/www/apps

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    # automatic check renovation needed every 12 hours
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      # .well-known directory
      - ./certbot/www:/var/www/certbot
